apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    chart: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.config.cephalopad }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/src/config.json
              subPath: config.json
              name: config-cephalopad
              readOnly: true
          resources:
            limits:
              memory: 1024Mi
              cpu: 200m
        - name: {{ .Values.config.citizen }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/src/config.json
              subPath: config.json
              name: config-citizen
              readOnly: true
          resources:
            limits:
              memory: 1024Mi
              cpu: 200m
        - name: {{ .Values.config.starworld }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/src/config.json
              subPath: config.json
              name: config-starworld
              readOnly: true
          resources:
            limits:
              memory: 1024Mi
              cpu: 200m
      volumes:
        - name: config-cephalopad
          secret:
            secretName: {{ .Values.config.cephalopad }}
        - name: config-citizen
          secret:
            secretName: {{ .Values.config.citizen }}
        - name: config-starworld
          secret:
            secretName: {{ .Values.config.starworld }}

