name: octunes
image:
  repository: 172.72.238.79:5000/octunes
  tag: 2.6.0
  pullPolicy: Always
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
config:
  cephalopad: octunes-cephalopad
  citizen: octunes-citizen
  starworld: octunes-starworld
